
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Aug  3 2020 22:10:18 EDT (Aug  4 2020 02:10:18 UTC)

// Verification Directory fv/fsm_output 

module register_WL2(clk, rst_b, d, q, wen);
  input clk, rst_b, wen;
  input [0:0] d;
  output [0:0] q;
  wire clk, rst_b, wen;
  wire [0:0] d;
  wire [0:0] q;
  wire n_0;
  DFFHQNx1_ASAP7_75t_R \q_reg[0] (.CLK (clk), .D (n_0), .QN (q));
  OAI21xp33_ASAP7_75t_R g14__8780(.A1 (wen), .A2 (q), .B (rst_b), .Y
       (n_0));
endmodule

module fsm_output_macro(OUT,INPUT_SPIKE,STORE_WEIGHT_0,STORE_WEIGHT_1,STORE_WEIGHT_2,ACLK);
  input INPUT_SPIKE, ACLK;
  input STORE_WEIGHT_0,STORE_WEIGHT_1,STORE_WEIGHT_2;
  output OUT;
  wire INPUT_SPIKE, ACLK;
  wire STORE_WEIGHT_0,STORE_WEIGHT_1,STORE_WEIGHT_2;
  wire OUT;
  wire UNCONNECTED_HIER_Z, n_0, w_0, weight_0;
  register_WL2 weight_0_reg(.clk (ACLK), .rst_b (INPUT_SPIKE), .d
       (UNCONNECTED_HIER_Z), .q (weight_0), .wen (w_0));
  NOR3xp33_ASAP7_75t_R g105__4296(.A (weight_0), .B (w_0), .C (n_0), .Y
       (OUT));
  NOR3xp33_ASAP7_75t_R g106__3772(.A (STORE_WEIGHT_2), .B
       (STORE_WEIGHT_0), .C (STORE_WEIGHT_1), .Y (w_0));
  INVx1_ASAP7_75t_R g107(.A (INPUT_SPIKE), .Y (n_0));
endmodule

