
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Jul 31 2020 17:06:16 EDT (Jul 31 2020 21:06:16 UTC)

// Verification Directory fv/pulse2edge 

module register_(clk, rst_b, d, q, wen);
  input clk, rst_b, wen;
  input [0:0] d;
  output [0:0] q;
  wire clk, rst_b, wen;
  wire [0:0] d;
  wire [0:0] q;
  wire n_0;
  DFFHQNx1_ASAP7_75t_R \q_reg[0] (.CLK (clk), .D (n_0), .QN (q));
  NAND2xp5_ASAP7_75t_R g14__8780(.A (rst_b), .B (d), .Y (n_0));
endmodule

module pulse2edge_area(EDGE_OUT, PULSE_IN, ACLK, GRST);
  input PULSE_IN, ACLK, GRST;
  output EDGE_OUT;
  wire PULSE_IN, ACLK, GRST;
  wire EDGE_OUT;
  wire UNCONNECTED_HIER_Z, n_0, temp;
  register_ inst_state_reg(.clk (ACLK), .rst_b (n_0), .d (EDGE_OUT),
       .q (temp), .wen (UNCONNECTED_HIER_Z));
  INVxp33_ASAP7_75t_R g3(.A (GRST), .Y (n_0));
  OR2x2_ASAP7_75t_R g4__4296(.A (PULSE_IN), .B (temp), .Y (EDGE_OUT));
endmodule

