/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "counter.v:1" *)
module counter(clk, rst, en, count);
  (* src = "counter.v:6" *)
  wire [3:0] _00_;
  (* src = "counter.v:10" *)
  wire [3:0] _01_;
  wire [3:0] _02_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [3:0] _03_;
  (* src = "counter.v:3" *)
  input clk;
  (* src = "counter.v:4" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "counter.v:3" *)
  input en;
  (* src = "counter.v:3" *)
  input rst;
  assign _02_[0] = en ? (* src = "counter.v:9" *) _01_[0] : count[0];
  assign _02_[1] = en ? (* src = "counter.v:9" *) _01_[1] : count[1];
  assign _02_[2] = en ? (* src = "counter.v:9" *) _01_[2] : count[2];
  assign _02_[3] = en ? (* src = "counter.v:9" *) _01_[3] : count[3];
  assign _00_[0] = rst ? (* src = "counter.v:7" *) 1'b0 : _02_[0];
  assign _00_[1] = rst ? (* src = "counter.v:7" *) 1'b0 : _02_[1];
  assign _00_[2] = rst ? (* src = "counter.v:7" *) 1'b0 : _02_[2];
  assign _00_[3] = rst ? (* src = "counter.v:7" *) 1'b0 : _02_[3];
  (* src = "counter.v:6" *)
  always @(posedge clk)
      count[0] <= _00_[0];
  (* src = "counter.v:6" *)
  always @(posedge clk)
      count[1] <= _00_[1];
  (* src = "counter.v:6" *)
  always @(posedge clk)
      count[2] <= _00_[2];
  (* src = "counter.v:6" *)
  always @(posedge clk)
      count[3] <= _00_[3];
  assign _03_[1] = count[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  count[0];
  assign _03_[2] = count[2] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _03_[1];
  assign _01_[0] = count[0] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _01_[1] = count[1] ^(* src = "<techmap.v>:263" *)  count[0];
  assign _01_[2] = count[2] ^(* src = "<techmap.v>:263" *)  _03_[1];
  assign _01_[3] = count[3] ^(* src = "<techmap.v>:263" *)  _03_[2];
endmodule
