/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "counter.v:1" *)
module counter(clk, rst, en, count);
  (* src = "counter.v:6" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "counter.v:10" *)
  wire [3:0] _32_;
  wire [3:0] _33_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [3:0] _34_;
  (* src = "counter.v:3" *)
  input clk;
  (* src = "counter.v:4" *)
  output [3:0] count;
  (* src = "counter.v:3" *)
  input en;
  (* src = "counter.v:3" *)
  input rst;
  NOT _35_ (
    .A(_16_),
    .Y(_02_)
  );
  NOT _36_ (
    .A(_13_),
    .Y(_04_)
  );
  NOR _37_ (
    .A(_04_),
    .B(_02_),
    .Y(_06_)
  );
  NOT _38_ (
    .A(_03_),
    .Y(_08_)
  );
  NAND _39_ (
    .A(_04_),
    .B(_02_),
    .Y(_10_)
  );
  NAND _40_ (
    .A(_10_),
    .B(_08_),
    .Y(_12_)
  );
  NOR _41_ (
    .A(_12_),
    .B(_06_),
    .Y(_05_)
  );
  NOT _42_ (
    .A(_01_),
    .Y(_14_)
  );
  NAND _43_ (
    .A(_13_),
    .B(_16_),
    .Y(_15_)
  );
  NOR _44_ (
    .A(_15_),
    .B(_14_),
    .Y(_17_)
  );
  NAND _45_ (
    .A(_15_),
    .B(_14_),
    .Y(_18_)
  );
  NAND _46_ (
    .A(_18_),
    .B(_08_),
    .Y(_19_)
  );
  NOR _47_ (
    .A(_19_),
    .B(_17_),
    .Y(_07_)
  );
  NAND _48_ (
    .A(_17_),
    .B(_30_),
    .Y(_20_)
  );
  NOT _49_ (
    .A(_20_),
    .Y(_21_)
  );
  NOT _50_ (
    .A(_30_),
    .Y(_22_)
  );
  NAND _51_ (
    .A(_06_),
    .B(_01_),
    .Y(_23_)
  );
  NAND _52_ (
    .A(_23_),
    .B(_22_),
    .Y(_24_)
  );
  NAND _53_ (
    .A(_24_),
    .B(_08_),
    .Y(_25_)
  );
  NOR _54_ (
    .A(_25_),
    .B(_21_),
    .Y(_09_)
  );
  NOT _55_ (
    .A(_31_),
    .Y(_26_)
  );
  NOR _56_ (
    .A(_20_),
    .B(_26_),
    .Y(_27_)
  );
  NAND _57_ (
    .A(_20_),
    .B(_26_),
    .Y(_28_)
  );
  NAND _58_ (
    .A(_28_),
    .B(_08_),
    .Y(_29_)
  );
  NOR _59_ (
    .A(_29_),
    .B(_27_),
    .Y(_11_)
  );
  DFF _60_ (
    .C(clk),
    .D(_00_[0]),
    .Q(count[0])
  );
  DFF _61_ (
    .C(clk),
    .D(_00_[1]),
    .Q(count[1])
  );
  DFF _62_ (
    .C(clk),
    .D(_00_[2]),
    .Q(count[2])
  );
  DFF _63_ (
    .C(clk),
    .D(_00_[3]),
    .Q(count[3])
  );
  assign _01_ = count[1];
  assign _16_ = en;
  assign _30_ = count[2];
  assign _31_ = count[3];
  assign _03_ = rst;
  assign _00_[0] = _05_;
  assign _00_[1] = _07_;
  assign _00_[2] = _09_;
  assign _00_[3] = _11_;
  assign _13_ = count[0];
endmodule
