/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "counter.v:1" *)
module counter(clk, rst, en, count);
  (* src = "counter.v:6" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "counter.v:10" *)
  wire [3:0] _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [3:0] _27_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [3:0] _28_;
  (* src = "counter.v:3" *)
  input clk;
  (* src = "counter.v:4" *)
  output [3:0] count;
  (* src = "counter.v:3" *)
  input en;
  (* src = "counter.v:3" *)
  input rst;
  AND2_X1 _29_ (
    .A1(_15_),
    .A2(_12_),
    .ZN(_02_)
  );
  NOR2_X1 _30_ (
    .A1(_15_),
    .A2(_12_),
    .ZN(_04_)
  );
  NOR3_X1 _31_ (
    .A1(_02_),
    .A2(_04_),
    .A3(_03_),
    .ZN(_05_)
  );
  NAND3_X1 _32_ (
    .A1(_01_),
    .A2(_15_),
    .A3(_12_),
    .ZN(_07_)
  );
  AOI21_X1 _33_ (
    .A(_01_),
    .B1(_15_),
    .B2(_12_),
    .ZN(_09_)
  );
  NOR2_X1 _34_ (
    .A1(_09_),
    .A2(_03_),
    .ZN(_11_)
  );
  AND2_X1 _35_ (
    .A1(_11_),
    .A2(_07_),
    .ZN(_06_)
  );
  NAND4_X1 _36_ (
    .A1(_01_),
    .A2(_15_),
    .A3(_20_),
    .A4(_12_),
    .ZN(_13_)
  );
  INV_X1 _37_ (
    .A(_20_),
    .ZN(_14_)
  );
  AOI21_X1 _38_ (
    .A(_03_),
    .B1(_07_),
    .B2(_14_),
    .ZN(_16_)
  );
  AND2_X1 _39_ (
    .A1(_16_),
    .A2(_13_),
    .ZN(_08_)
  );
  NAND2_X1 _40_ (
    .A1(_13_),
    .A2(_21_),
    .ZN(_17_)
  );
  INV_X1 _41_ (
    .A(_21_),
    .ZN(_18_)
  );
  NAND4_X1 _42_ (
    .A1(_02_),
    .A2(_01_),
    .A3(_20_),
    .A4(_18_),
    .ZN(_19_)
  );
  AOI21_X1 _43_ (
    .A(_03_),
    .B1(_19_),
    .B2(_17_),
    .ZN(_10_)
  );
  DFF_X1 _44_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(count[0]),
    .QN(_23_)
  );
  DFF_X1 _45_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(count[1]),
    .QN(_24_)
  );
  DFF_X1 _46_ (
    .CK(clk),
    .D(_00_[2]),
    .Q(count[2]),
    .QN(_25_)
  );
  DFF_X1 _47_ (
    .CK(clk),
    .D(_00_[3]),
    .Q(count[3]),
    .QN(_26_)
  );
  assign _01_ = count[1];
  assign _15_ = en;
  assign _20_ = count[2];
  assign _21_ = count[3];
  assign _03_ = rst;
  assign _00_[0] = _05_;
  assign _00_[1] = _06_;
  assign _00_[2] = _08_;
  assign _00_[3] = _10_;
  assign _12_ = count[0];
endmodule
